-- +goose Up
-- +goose StatementBegin
CREATE TABLE "users" (
    "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid" uuid DEFAULT gen_random_uuid(),
    "username" varchar UNIQUE,
    "password_hash" varchar,
    "full_name" varchar,
    "role_id" int,
    "created_by" int,
    "updated_by" int,
    "created_at" timestamp,
    "updated_at" timestamp
);

CREATE TABLE "roles" (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "privilege" text,
  "created_by" int,
  "updated_by" int,
  "created_at" timestamp,
  "updated_at" timestamp
);


ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
-- +goose StatementEnd
