// Code generated by MockGen. DO NOT EDIT.
// Source: user.service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "github.com/dwilanang/psp/internal/user/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateSalary mocks base method.
func (m *MockService) CreateSalary(request *dto.UserSalaryRequest) (dto.UserSalaryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSalary", request)
	ret0, _ := ret[0].(dto.UserSalaryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSalary indicates an expected call of CreateSalary.
func (mr *MockServiceMockRecorder) CreateSalary(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSalary", reflect.TypeOf((*MockService)(nil).CreateSalary), request)
}

// Register mocks base method.
func (m *MockService) Register(request *dto.UserRequest) (dto.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", request)
	ret0, _ := ret[0].(dto.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockServiceMockRecorder) Register(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockService)(nil).Register), request)
}
